# Imports

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import csv
from sklearn.preprocessing import MinMaxScaler
from math import sqrt
from sklearn.metrics import mean_squared_error 
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Importing and Splitting data

In [17]:
file = pd.read_csv("audi.csv", quotechar='"', skipinitialspace=True)

modelEncoder = LabelEncoder()
modelEncoder.fit(file["model"])
file["model"] = modelEncoder.transform(file["model"])

transmissionEncoder = LabelEncoder()
transmissionEncoder.fit(file["transmission"])
file["transmission"] = transmissionEncoder.transform(file["transmission"])

fuelTypeEncoder = LabelEncoder()
fuelTypeEncoder.fit(file["fuelType"])
file["fuelType"] = fuelTypeEncoder.transform(file["fuelType"])

file = file.head(1000)
# X = file.drop(columns = ['price'])
# Y = file.price
# print(file)

X = file.drop(['price'], axis = 1).to_numpy()
Y = file['price'].values.reshape(-1,1)
# X = file[['year', 'mileage', 'tax', 'mpg', 'engineSize']].to_numpy() #dtype = 'int'

print(X)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 601)

[[0.000e+00 2.017e+03 1.000e+00 ... 1.500e+02 5.540e+01 1.400e+00]
 [5.000e+00 2.016e+03 0.000e+00 ... 2.000e+01 6.420e+01 2.000e+00]
 [0.000e+00 2.016e+03 1.000e+00 ... 3.000e+01 5.540e+01 1.400e+00]
 ...
 [5.000e+00 2.019e+03 2.000e+00 ... 1.500e+02 3.770e+01 3.000e+00]
 [1.000e+01 2.017e+03 2.000e+00 ... 1.500e+02 3.400e+01 3.000e+00]
 [4.000e+00 2.018e+03 2.000e+00 ... 1.500e+02 3.530e+01 3.000e+00]]


# Using Scikit-Learn

In [18]:
myTree = DecisionTreeRegressor(random_state = 601)
myTree.fit(X_train, Y_train)
print("R Squared: ", myTree.score(X_test, Y_test))

R Squared:  0.8469942517214841


# Visualising Decsion Tree:

In [19]:
treeView = DecisionTreeRegressor(random_state = 601, max_depth = 3)
treeView.fit(X_train,Y_train)

from sklearn.tree import plot_tree
plt.figure(figsize=(8,3), dpi = 150)
plot_tree(treeView, feature_names = X.columns, filled=True);

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

<Figure size 1200x450 with 0 Axes>

# Entropy

In [6]:
# def calc_total_entropy(train_data, label, class_list):
#     total_row = train_data.shape[0]
#     total_entr = 0 #l
    
#     for c in class_list: 
#         total_class_count = train_data[train_data[label] == c].shape[0] 
#         total_class_entr = - (total_class_count/total_row)*np.log2(total_class_count/total_row) 
#         total_entr += total_class_entr 
    
#     return total_entr



#  def entropy(self, y):
#         entropy = 0
#         labels = np.unique(y)
#         for label in labels:
#             label_examples = y[y == label]
#             pl = len(label_examples) / len(y)
#             entropy += -pl * np.log2(pl)
#         return entropy

# RMSE

In [7]:
def rmse(h, y):
  return sqrt(mean_squared_error(h, y))

In [77]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, var_red=None, value=None):
        
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
#         self.var_red = var_red
        self.value = value #leaf

In [98]:
class DTRegressor():
    def __init__(self, minSamples = 2, maxDepth = 2):
        self.root = None
        self.minSamples = minSamples
        self.maxDepth = maxDepth
        
    def entropy(self, y): #need to change method
        entropy = 0
        
        labels = np.unique(y)
        # loop over each unique value
        for label in labels:
            # find elements in y that are equal to that label
            label_examples = y[y == label]
            # get ratio of the label
            pl = len(label_examples) / len(y)
            # calculate entropy
            entropy += -pl * np.log2(pl)
        return entropy
        
    def infoGain(self, parent, leftNode, rightNode): #need to checkkk
        print("HERE 5")
        leftWeight = len(leftNode) / len(parent)
        rightWeight = len(rightNode) / len(parent)
        
#         reduction = np.var(parent) - (leftWeight * np.var(leftNode) + rightWeight * np.var(rightNode))
#         print ("REDUCTION: ", reduction)

        parent_entropy = self.entropy(parent)
        entropy_left, entropy_right = self.entropy(leftNode), self.entropy(rightNode)
        # calculate weighted entropy 
        weighted_entropy = leftWeight * entropy_left + rightWeight * entropy_right
        # calculate information gain 
        information_gain = parent_entropy - weighted_entropy
#         print(information_gain)

        return information_gain
#         return reduction
        
    def splitTree(self, dataset, feature, threshold):
        print("HERE 4")
        leftBranch = []
        rightBranch = []
        for i in dataset:
            if i[feature] <= threshold:
                leftBranch.append(i)
            else:
                rightBranch.append(i)
        rightBranch = np.array(rightBranch)
        leftBranch = np.array(leftBranch)
        return leftBranch, rightBranch
        
    def bestSplit(self, dataset, X):
        print("HERE 3")
        bestSplitt = {'gain':- 1}
        
        for i in range(X.shape[1]): #feature_index = i
            feature = dataset[:, i] #current feature selected
            thresholds = np.unique(feature)
#             print(thresholds)
            for j in thresholds: #threshold = j
                # get current split
                leftSide, rightSide = self.splitTree(dataset, i, j) #splits tree into 2 branches
            
                if (len(leftSide) > 0 and len(rightSide) > 0 ):
                    parent = dataset[:, -1]
                    leftNode = leftSide[:, -1]
                    rightNode = rightSide[:, -1]

                    gain = self.infoGain(parent, leftNode, rightNode) 
                    
                    if gain > bestSplitt["gain"]:
                        bestSplitt["feature"] = feature
                        bestSplitt["thresholds"] = thresholds
                        bestSplitt["leftSide"] = leftSide
                        bestSplitt["rightSide"] = rightSide
                        bestSplitt["gain"] = gain
                
        return bestSplitt
        
    def treeBuild(self, dataset, currentDepth = 0):
        print("HERE 2")
        X = dataset[:,:-1]
        Y = dataset[:,-1] #Split training into features and labels
#         samplesNumb = X.shape[0]
#         featuresNumb = X.shape[1]
        
        #iterates until this condition is met
        if X.shape[0] >= self.minSamples and currentDepth <= self.maxDepth: 
            bestSplit = self.bestSplit(dataset, X)
            
            if bestSplit["gain"] > 0:
                leftTree = self.treeBuild(bestSplit["leftSide"], currentDepth + 1)
                rightTree = self.treeBuild(bestSplit["rightSide"], currentDepth + 1)
                
                decision = Node(bestSplit["feature"], bestSplit["thresholds"], leftTree, rightTree, bestSplit["gain"])
                return decision
            
        leaf = self.leafValue(Y) #need to complete method that finds leaf value
        val = Node(value = leadValue)
        return val
        
        
    def fit(self, X, Y):
        print("HERE 1")
        dataset = np.concatenate((X, Y), axis=1) #Joins training data back together
        self.root = self.treeBuild(dataset)

In [96]:
myTree = DTRegressor(2, 2) #create model instance
myTree.fit(X_train, Y_train)

HERE 1
HERE 2
HERE 3
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4

HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5

HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 4
HERE 5
HERE 4
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5
HERE 4
HERE 5

AttributeError: 'DTRegressor' object has no attribute 'leafValue'