# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import csv
from sklearn.preprocessing import MinMaxScaler
from math import sqrt
from sklearn.metrics import mean_squared_error 
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Importing and Splitting data

In [16]:
file = pd.read_csv("audi.csv", quotechar='"', skipinitialspace=True)

modelEncoder = LabelEncoder()
modelEncoder.fit(file["model"])
file["model"] = modelEncoder.transform(file["model"])

transmissionEncoder = LabelEncoder()
transmissionEncoder.fit(file["transmission"])
file["transmission"] = transmissionEncoder.transform(file["transmission"])

fuelTypeEncoder = LabelEncoder()
fuelTypeEncoder.fit(file["fuelType"])
file["fuelType"] = fuelTypeEncoder.transform(file["fuelType"])

file = file.head(1000)
# X = file.drop(columns = ['price'])
# Y = file.price
# print(file)

# X = file.drop(['price'], axis = 1).to_numpy(dtype = 'int')
Y = file['price'].values.reshape(-1,1)
X = file[['year', 'mileage', 'tax', 'mpg', 'engineSize']].to_numpy() #dtype = 'int'

print(X)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 601)

[[2.0170e+03 1.5735e+04 1.5000e+02 5.5400e+01 1.4000e+00]
 [2.0160e+03 3.6203e+04 2.0000e+01 6.4200e+01 2.0000e+00]
 [2.0160e+03 2.9946e+04 3.0000e+01 5.5400e+01 1.4000e+00]
 ...
 [2.0190e+03 7.4610e+03 1.5000e+02 3.7700e+01 3.0000e+00]
 [2.0170e+03 3.7492e+04 1.5000e+02 3.4000e+01 3.0000e+00]
 [2.0180e+03 3.6715e+04 1.5000e+02 3.5300e+01 3.0000e+00]]


# Using Scikit-Learn

In [3]:
myTree = DecisionTreeRegressor(random_state = 601)
myTree.fit(X_train, Y_train)
print("R Squared: ", myTree.score(X_test, Y_test))

R Squared:  0.6213703125742205


# Visualising Decsion Tree:

In [17]:
treeView = DecisionTreeRegressor(random_state = 601, max_depth = 3)
treeView.fit(X_train,Y_train)

from sklearn.tree import plot_tree
plt.figure(figsize=(8,3), dpi = 150)
plot_tree(treeView, feature_names = X.columns, filled=True);

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

<Figure size 1200x450 with 0 Axes>

# Entropy

In [ ]:
# def calc_total_entropy(train_data, label, class_list):
#     total_row = train_data.shape[0]
#     total_entr = 0 #l
    
#     for c in class_list: 
#         total_class_count = train_data[train_data[label] == c].shape[0] 
#         total_class_entr = - (total_class_count/total_row)*np.log2(total_class_count/total_row) 
#         total_entr += total_class_entr 
    
#     return total_entr



#  def entropy(self, y):
#         entropy = 0
#         labels = np.unique(y)
#         for label in labels:
#             label_examples = y[y == label]
#             pl = len(label_examples) / len(y)
#             entropy += -pl * np.log2(pl)
#         return entropy

# RMSE

In [ ]:
def rmse(h, y):
  return sqrt(mean_squared_error(h, y))

In [5]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, var_red=None, value=None):
        
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.var_red = var_red
        self.value = value #leaf

In [93]:
class DTRegressor():
    def __init__(self, minSamples = 2, maxDepth = 2):
        self.root = None
        self.minSamples = minSamples
        self.maxDepth = maxDepth
        
    def splitTree(self, dataset, feature, threshold):
        print("hello")
        return
        
    def bestSplit(self, dataset, X):
        bestSplitt = {}
        
        for i in range(X.shape[1]): #feature_index = i
            feature = dataset[:, i] #current feature selected
            thresholds = np.unique(feature)
#             print(thresholds)
            for j in thresholds: #threshold = j
                # get current split
                leftSide, rightSide = self.splitTree(dataset, i, j) #splits tree into 2 branches
                print(leftSide)
        return
        
    def treeBuild(self, dataset, currentDepth = 0):
        X = dataset[:,:-1]
        Y = dataset[:,-1] #Split training into features and labels
#         samplesNumb = X.shape[0]
#         featuresNumb = X.shape[1]
        
        #iterates until this condition is met
        if X.shape[0] >= self.minSamples and currentDepth <= self.maxDepth: 
            bestSplit = self.bestSplit(dataset, X)
            
#         print(n_features)
        
        
    def fit(self, X, Y):
        dataset = np.concatenate((X, Y), axis=1) #Joins training data back together
        self.root = self.treeBuild(dataset)

In [94]:
myTree = DTRegressor(2, 2) #create model instance
myTree.fit(X_train,Y_train)

hello


TypeError: cannot unpack non-iterable NoneType object